language: node_js
node_js: node
branches:
  only:
  - vue-press
before_install:
- export TZ='Asia/Shanghai'
- openssl aes-256-cbc -K $encrypted_44750c81711d_key -iv $encrypted_44750c81711d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
install:
- npm i
before_script:
- git config user.name "Travis-CI"
- git config user.email "smalltime153@gmail.com"
script: npm run build
after_success:
- cd public
- rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./* "${SERVER_USER}"@"${SERVER_IP}":"${TARGET_PATH}"
- echo -e "Publish to Server Done\n"
- git init
- echo 'blog.abplan.top' > CNAME
- git add -A .
- git status
- git commit -a -m "Travis-CI Deployed to Github"
- git remote add origin https://${GITHUB_TOKEN}@${GH_GITHUB}
- git push -f origin master
- echo -e "Publish to Github Done\n"
env:
  global:
  - GH_GITHUB: github.com/FearwareX/xiaoshiguang123.github.io.git
  - secure: SqKbIt6Af27Ii/GAisD5spSTTaUrczHtGTK98L/uJa7J2RceIM+EDnajbv6GLV/b2rWMenkSb6+tOWzEfP2dp0HsMPhLXdvAjmB7rqTBCFgVvrmDRxCa17+WpA78N45FzvNPCh+I4WIiQI6IgC93JvWyzHIO+fHi+EC7rZpRk5ev8UAkznYskrWCLlLoeXoSwoFsxNaqyeVKXC5sW2VFs3pJPhFuWPpyTl8x1DEjy7JEFP2E0DMmWq+OCrPzXTSUBPgjd9qp9V4J5IP3UyZr22LMcJgpvdj3tHl7yb7GgUDQNbRl3Z1ThKYLvzVjpVDnexCdp2hzWqTuxIR9kOw+eh+cbG9CaDW+573x8C/Pj/6GaBA5UUBsmXyGaRsu9rAEC1DHwPTgJ9YPx6+Zq9XczAzB/Ar79/tXh10Xf24/VLBUbVmgREwCLCg0OBdVDm5KemvUzXasE0o8WbFLWnvOhbSgBT5QPWA/h9DzIgDIu//xL6XOvkM2DcxnRSsTkCxhxhUs0l/1hTEmzcrIHFZ0sEU1cUbqKviqHpZHRuHDCpMu7/45wm9f0tRAZpCaeN5CyX463KtDZtdNd8lswP4sCE3IT4kZcPlUYD3mr528JyaNAzVuNmUG/b5S3JBlx1PqpELMF9/cagkS0TnJ2mGktibBxOQh+St2AEjQXlmxrtQ=
